# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  #  zenwaveexample-app:
  #    image: zenwaveexample
  #    environment:
  #      - _JAVA_OPTIONS=-Xmx512m -Xms256m
  #      - SPRING_PROFILES_ACTIVE=prod,api-docs
  #      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
  #      - SPRING_DATA_MONGODB_URI=mongodb://zenwaveexample-mongodb:27017
  #      - SPRING_DATA_MONGODB_DATABASE=ZenWaveApiExample
  #      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
  #      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
  #      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
  #      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  #      - SPRING_ELASTICSEARCH_REST_URIS=http://zenwaveexample-elasticsearch:9200
  #    # If you want to expose these ports outside your dev PC,
  #    # remove the "127.0.0.1:" prefix
  #    ports:
  #      - 127.0.0.1:8080:8080
  zenwaveexample-mongodb:
    image: mongo:4.4.10
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:27017:27017
    # volumes:
    #   - ~/volumes/jhipster/ZenWaveApiExample/mongodb/:/data/db/
  zenwaveexample-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    # volumes:
    #   - ~/volumes/jhipster/ZenWaveApiExample/elasticsearch/:/usr/share/elasticsearch/data/
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - 'discovery.type=single-node'
  zenwaveexample-kafka:
    image: confluentinc/cp-kafka:7.2.1
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
    ports:
      - 9092:9092
  zenwaveexample-zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
