package io.zenwave360.sdk.plugins.support;

public enum MethodBodyCase {
    ASYNC_DELEGATE,
    ENTITY_LIFECYCLE_UPDATE_OPTIONAL,
    ENTITY_LIFECYCLE_UPDATE_REQUIRED,
    ENTITY_DELETE,
    ENTITY_LIST,
    ENTITY_PATCH_OPTIONAL,
    ENTITY_UPDATE_OPTIONAL,
    ENTITY_UPDATE_REQUIRED,
    ENTITY_TRANSITION_OPTIONAL,
    ENTITY_TRANSITION_REQUIRED,
    ENTITY_GET_OPTIONAL,
    ENTITY_GET_REQUIRED,
    ENTITY_QUERY_BY_INPUT_OPTIONAL,
    ENTITY_QUERY_BY_INPUT_REQUIRED,
    ENTITY_NEW_INSTANCE_RETURN,
    ENTITY_NEW_INSTANCE_VOID,
    FALLBACK_TODO
}
