name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
#projects: ["octo-org/1", "octo-org/44"]
assignees:
  - ivangsa
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: ZenWave Version
      description: Which version of ZenWave are you using?
      placeholder: 2.3.0
    validations:
      required: true
  - type: dropdown
    id: execution
    attributes:
      label: Execution Environment
      description: How did you executed ZenWave SDK?
      options:
        - JBang Alias (CLI)
        - Maven Plugin
        - Other
    validations:
      required: true
  - type: dropdown
    id: plugin
    attributes:
      label: ZenWave Plugin
      description: Which ZenWave plugin are you using?
      options:
        - BackendApplicationDefaultPlugin
        - ZDLToOpenAPIPlugin
        - ZDLToAsyncAPIPlugin
        - OpenAPIControllersPlugin
        - AsyncAPIGeneratorPlugin
        - SpringWebTestClientPlugin
        - AvroSchemaGeneratorPlugin
        - AsyncApiJsonSchema2PojoPlugin
        - SpringCloudStreams3Plugin
        - SpringCloudStreams3AdaptersPlugin
        - ZdlToMarkdownPlugin
        - JDLToAsyncAPIPlugin
        - OpenAPIToJDLPlugin
        - ZdlToJsonPlugin
        - BackendApplicationKotlinTemplates
        - OpenAPIControllersKotlinTemplates
        - SpringWebTestClientKotlinTemplates
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please, also attach relevant parts of your ZDL file.
    validations:
      required: true
  - type: textarea
    id: zdl
    attributes:
      label: Relevant ZDL Model
      description: Please, also attach relevant parts of your ZDL file.

