blank_issues_enabled: false
contact_links:
  - name: Question/Discussion
    url: https://github.com/ZenWave360/zenwave-sdk/discussions/new
    about: I have a question or topic to discuss which is not a bug nor new feature.
