asyncapi: 3.0.0
id: url:merchandising.inventory.inventory-adjustment
info:
  title: Inventory Adjustment Topic Provider
  version: 1.0.0
  description: This specification defines the topics provided by the inventory adjustment service from the provider point of view.

servers:
  dev:
    host: kafka-dev.example.com
    protocol: kafka
  staging:
    host: kafka-staging.example.com
    protocol: kafka
  production:
    host: kafka-production.example.com
    protocol: kafka

channels:
  reserve-stock-command:
    address: merchandising.inventory.inventory-adjustment.reserve-stock.command.avro.v0
    summary: Reserve Stock Command
    description: This channel is used to request reservation of stock for a product at a location.
    messages:
      ReserveStockCommand:
        payload:
          schemaFormat: 'application/vnd.apache.avro+json;version=1.9.0'
          schema:
            $ref: './avro/ReserveStockCommand.avsc'
        traits:
          - $ref: '../../../master/kafka-bindings.yml#/components/messageTraits/kafkaKeyString'
          - $ref: '../../../master/kafka-bindings.yml#/components/messageTraits/kafkaTopicRecordNameStrategy'
          - $ref: '../../../master/kafka-bindings.yml#/components/messageTraits/kafkaBackwardCompatibility'
    bindings:
      $ref: '../../../master/kafka-bindings.yml#/components/channelBindings/kafkaGold'

  reserve-stock-response:
    address: merchandising.inventory.inventory-adjustment.reserve-stock.response.avro.v0
    summary: Reserve Stock Response
    description: This channel informs the result of a reserve stock request.
    messages:
      ReserveStockResponse:
        payload:
          schemaFormat: 'application/vnd.apache.avro+json;version=1.9.0'
          schema:
            $ref: './avro/ReserveStockResponse.avsc'
        traits:
          - $ref: '../../../master/kafka-bindings.yml#/components/messageTraits/kafkaKeyString'
          - $ref: '../../../master/kafka-bindings.yml#/components/messageTraits/kafkaTopicRecordNameStrategy'
          - $ref: '../../../master/kafka-bindings.yml#/components/messageTraits/kafkaForwardCompatibility'
    bindings:
      $ref: '../../../master/kafka-bindings.yml#/components/channelBindings/kafkaGold'

  inventory-adjusted:
    address: merchandising.inventory.inventory-adjustment.inventory-adjusted.event.avro.v0
    summary: Inventory Adjusted Event
    description: This channel informs that inventory was adjusted for a product at a specific location.
    messages:
      InventoryAdjustedEvent:
        payload:
          schemaFormat: 'application/vnd.apache.avro+json;version=1.9.0'
          schema:
            $ref: './avro/InventoryAdjusted.avsc'
        traits:
          - $ref: '../../../master/kafka-bindings.yml#/components/messageTraits/kafkaKeyString'
          - $ref: '../../../master/kafka-bindings.yml#/components/messageTraits/kafkaTopicRecordNameStrategy'
          - $ref: '../../../master/kafka-bindings.yml#/components/messageTraits/kafkaForwardCompatibility'
    bindings:
      $ref: '../../../master/kafka-bindings.yml#/components/channelBindings/kafkaGold'

operations:
  doReserveStockCommand:
    action: receive
    channel:
      $ref: '#/channels/reserve-stock-command'
    bindings:
      kafka:
        x-principal: "merchandising.inventory.inventory-adjustment"
        groupId: "merchandising.inventory.inventory-adjustment"
        x-error-topics:
          addressTemplate: "${groupId}.__.${channel.address}.${suffix}"
          retryTopics: 3
          retry:
            $ref: '../../../master/kafka-bindings.yml#/components/x-error-topics/retry/silver'
          dlq:
            $ref: '../../../master/kafka-bindings.yml#/components/x-error-topics/dlq/standard'

  onReserveStockResponse:
    action: send
    channel:
      $ref: '#/channels/reserve-stock-response'
    traits:
      - $ref: '#/components/operationTraits/kafkaPrincipal'
      - $ref: '#/components/operationTraits/kafkaClientId'

  onInventoryAdjustedEvent:
    action: send
    channel:
      $ref: '#/channels/inventory-adjusted'
    traits:
      - $ref: '#/components/operationTraits/kafkaPrincipal'
      - $ref: '#/components/operationTraits/kafkaClientId'

components:
  operationTraits:
    kafkaPrincipal:
      bindings:
        kafka:
          x-principal: "merchandising.inventory.inventory-adjustment"
    kafkaClientId:
      bindings:
        kafka:
          clientId:
            type: "string"
            enum: ["merchandising.inventory.inventory-adjustment"]
    kafkaConsumerGroup:
      bindings:
        kafka:
          groupId:
            type: "string"
            enum: ["merchandising.inventory.inventory-adjustment"]
