name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: ZenWave360/release-workflows/.github/workflows/main-maven.yml@main
    with:
      jacoco-csv-files: >
        ./plugins/asyncapi-spring-cloud-streams3/target/site/jacoco/jacoco.csv
        ./plugins/avro-schema-compiler/target/site/jacoco/jacoco.csv
        ./plugins/asyncapi-generator/target/site/jacoco/jacoco.csv
        ./plugins/java-to-jdl/target/site/jacoco/jacoco.csv
        ./plugins/java-to-asyncapi/target/site/jacoco/jacoco.csv
        ./plugins/backend-application-default/target/site/jacoco/jacoco.csv
        ./plugins/openapi-controllers/target/site/jacoco/jacoco.csv
        ./plugins/zdl-to-openapi/target/site/jacoco/jacoco.csv
        ./plugins/jdl-to-asyncapi/target/site/jacoco/jacoco.csv
        ./plugins/zdl-to-asyncapi/target/site/jacoco/jacoco.csv
        ./plugins/zdl-to-markdown/target/site/jacoco/jacoco.csv
        ./plugins/openapi-spring-webtestclient/target/site/jacoco/jacoco.csv
        ./plugins/openapi-karate/target/site/jacoco/jacoco.csv
        ./plugins/asyncapi-ops/target/site/jacoco/jacoco.csv
        ./zenwave-sdk-cli/target/site/jacoco/jacoco.csv
        ./plugins/customizations/kotlin-backend-application/target/site/jacoco/jacoco.csv
