name: Create Maven Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release Version:"
        required: true
      developmentVersion:
        description: "Next Development Version:"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure Git User
        run: |
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git config user.name ${{ github.actor }}

      - name: Prepare Release
        run: |
          mvn -B release:prepare -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
          mvn -B release:clean
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create Pull Request (Main)
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'Release ${{ github.event.inputs.releaseVersion }}'
          branch: release/${{ github.event.inputs.releaseVersion }}
          title: 'Release ${{ github.event.inputs.releaseVersion }}'
          body: 'Release ${{ github.event.inputs.releaseVersion }}'
          labels: 'release'

      - name: Enable Pull Request Automerge (Main)
        run: gh pr merge --merge --auto --delete-branch "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Push Release Tag
        run: git push --tags
